[ {
  "boro" : "BRONX",
  "building" : "1007",
  "phone" : "7188924968",
  "camis" : "30075445",
  "dba" : "MORRIS PARK BAKE SHOP",
  "street" : "MORRIS PARK AVE",
  "zipcode" : "10462",
  "inspection_type" : "Trans Fat / Second Compliance Inspection",
  "cuisine_description" : "Bakery",
  "inspection_date" : "2012-05-03T00:00:00",
  "critical_flag" : "Not Applicable",
  "record_date" : "2015-11-06T06:01:00",
  "action" : "No violations were recorded at the time of this inspection."
}
, {
  "boro" : "BROOKLYN",
  "building" : "469       ",
  "phone" : "7182875005",
  "camis" : "30112340",
  "dba" : "WENDY'S",
  "street" : "FLATBUSH AVENUE                                   ",
  "zipcode" : "11225",
  "inspection_type" : "Cycle Inspection / Initial Inspection",
  "grade_date" : "2015-05-07T00:00:00",
  "score" : "12",
  "cuisine_description" : "Hamburgers",
  "violation_description" : "Food Protection Certificate not held by supervisor of food operations.",
  "inspection_date" : "2015-05-07T00:00:00",
  "critical_flag" : "Critical",
  "violation_code" : "04A",
  "record_date" : "2015-11-06T06:01:00",
  "action" : "Violations were cited in the following area(s).",
  "grade" : "A"
}
, {
  "boro" : "MANHATTAN",
  "building" : "351       ",
  "phone" : "2122452912",
  "camis" : "30191841",
  "dba" : "DJ REYNOLDS PUB AND RESTAURANT",
  "street" : "WEST   57 STREET                                  ",
  "zipcode" : "10019",
  "inspection_type" : "Cycle Inspection / Re-inspection",
  "grade_date" : "2015-09-21T00:00:00",
  "score" : "8",
  "cuisine_description" : "Irish",
  "violation_description" : "Food not protected from potential source of contamination during storage, preparation, transportation, display or service.",
  "inspection_date" : "2015-09-21T00:00:00",
  "critical_flag" : "Critical",
  "violation_code" : "06C",
  "record_date" : "2015-11-06T06:01:00",
  "action" : "Violations were cited in the following area(s).",
  "grade" : "A"
}
, {
  "boro" : "QUEENS",
  "building" : "8825",
  "phone" : "7183350505",
  "camis" : "40356151",
  "dba" : "BRUNOS ON THE BOULEVARD",
  "street" : "ASTORIA BOULEVARD",
  "zipcode" : "11369",
  "inspection_type" : "Cycle Inspection / Re-inspection",
  "grade_date" : "2015-05-29T00:00:00",
  "score" : "12",
  "cuisine_description" : "American ",
  "violation_description" : "Evidence of mice or live mice present in facility's food and/or non-food areas.",
  "inspection_date" : "2015-05-29T00:00:00",
  "critical_flag" : "Critical",
  "violation_code" : "04L",
  "record_date" : "2015-11-06T06:01:00",
  "action" : "Violations were cited in the following area(s).",
  "grade" : "A"
}
, {
  "boro" : "STATEN ISLAND",
  "building" : "2206      ",
  "phone" : "7186985800",
  "camis" : "40356442",
  "dba" : "KOSHER ISLAND",
  "street" : "VICTORY BOULEVARD                                 ",
  "zipcode" : "10314",
  "inspection_type" : "Cycle Inspection / Initial Inspection",
  "score" : "14",
  "cuisine_description" : "Jewish/Kosher",
  "violation_description" : "Non-food contact surface improperly constructed. Unacceptable material used. Non-food contact surface or equipment improperly maintained and/or not properly sealed, raised, spaced or movable to allow accessibility for cleaning on all sides, above and underneath the unit.",
  "inspection_date" : "2014-04-24T00:00:00",
  "critical_flag" : "Not Critical",
  "violation_code" : "10F",
  "record_date" : "2015-11-06T06:01:00",
  "action" : "Violations were cited in the following area(s)."
}]